[package]
name = "vulka"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.37.3"
ash-window = "0.12.0"
may = "0.3.42"
num_cpus = "1.16.0"
winit = "0.28.0"
raw-window-handle = "0.5"
shaderc = "0.8.3"
